package com.paybridge.Models.DTOs;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.paybridge.Models.Enums.PaymentStatus;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * Response DTO returned after creating a payment.
 * This is what YOUR system returns to the MERCHANT after processing their payment request.
 *
 * The merchant uses this information to:
 * 1. Redirect their customer to the checkout URL (for hosted checkout)
 * 2. Use the clientSecret in their frontend (for embedded checkout)
 * 3. Track the payment using the id
 * 4. Display the status to their customer
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class PaymentResponse {

    /**
     * Unique payment ID generated by YOUR system
     * Format: UUID (e.g., "550e8400-e29b-41d4-a716-446655440000")
     *
     * The merchant should store this in their database to:
     * - Query payment status later
     * - Match webhook notifications
     * - Handle refunds
     */
    private UUID id;

    /**
     * Current status of the payment
     * Possible values:
     * - PENDING: Payment created, waiting for customer action
     * - PROCESSING: Customer is completing payment
     * - SUCCEEDED: Payment completed successfully
     * - FAILED: Payment failed
     * - CANCELLED: Customer cancelled payment
     */
    private PaymentStatus status;

    /**
     * Hosted checkout URL where customer should be redirected
     * This is a URL on the payment provider's domain (Stripe, Flutterwave, etc.)
     *
     * Example: "https://checkout.stripe.com/pay/cs_test_abc123"
     *
     * The merchant's frontend should redirect the customer here:
     * window.location.href = checkoutUrl
     */
    private String checkoutUrl;

    /**
     * Client secret for embedded/custom checkout flows
     * Used when merchant wants to embed payment form on their own website
     *
     * Example: "pi_3abc123_secret_def456"
     *
     * The merchant passes this to their frontend SDK:
     * stripe.confirmPayment({ clientSecret: '...' })
     */
    private String clientSecret;

    /**
     * Timestamp when payment was created in YOUR system
     */
    private Instant createdAt;

    /**
     * Amount of the payment
     * Same as what merchant requested
     */
    private BigDecimal amount;

    /**
     * Currency of the payment
     * Same as what merchant requested
     */
    private String currency;

    /**
     * Which payment provider is handling this payment
     * Example: "stripe", "flutterwave", "paystack"
     */
    private String provider;

    /**
     * Provider's reference ID for this payment
     * This is the payment ID in the provider's system
     *
     * Example for Stripe: "pi_3abc123def456"
     * Example for Flutterwave: "2786172"
     */
    private String providerReference;

    /**
     * Custom metadata that merchant provided
     * Returned as-is for merchant's convenience
     */
    private Map<String, String> metadata;

    /**
     * Expiration time for this payment
     * After this time, the checkout URL/clientSecret becomes invalid
     * Typically 30 minutes to 1 hour
     */
    private Instant expiresAt;

    /**
     * Human-readable message about the payment
     * Example: "Payment created successfully"
     * Example: "Awaiting customer confirmation"
     */
    private String message;

    // ========== CONSTRUCTORS ==========

    public PaymentResponse() {
    }

    // Success response with checkout URL
    public static PaymentResponse hosted(UUID id, PaymentStatus status, String checkoutUrl,
                                         BigDecimal amount, String currency, String provider) {
        PaymentResponse response = new PaymentResponse();
        response.id = id;
        response.status = status;
        response.checkoutUrl = checkoutUrl;
        response.amount = amount;
        response.currency = currency;
        response.provider = provider;
        response.createdAt = Instant.now();
        response.message = "Payment created successfully. Redirect customer to checkout URL.";
        return response;
    }

    // Success response with client secret (for embedded checkout)
    public static PaymentResponse embedded(UUID id, PaymentStatus status, String clientSecret,
                                           BigDecimal amount, String currency, String provider) {
        PaymentResponse response = new PaymentResponse();
        response.id = id;
        response.status = status;
        response.clientSecret = clientSecret;
        response.amount = amount;
        response.currency = currency;
        response.provider = provider;
        response.createdAt = Instant.now();
        response.message = "Payment created successfully. Use client secret in your frontend.";
        return response;
    }

    // ========== GETTERS AND SETTERS ==========

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public PaymentStatus getStatus() {
        return status;
    }

    public void setStatus(PaymentStatus status) {
        this.status = status;
    }

    public String getCheckoutUrl() {
        return checkoutUrl;
    }

    public void setCheckoutUrl(String checkoutUrl) {
        this.checkoutUrl = checkoutUrl;
    }

    public String getClientSecret() {
        return clientSecret;
    }

    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getProviderReference() {
        return providerReference;
    }

    public void setProviderReference(String providerReference) {
        this.providerReference = providerReference;
    }

    public Map<String, String> getMetadata() {
        return metadata;
    }

    public void setMetadata(Map<String, String> metadata) {
        this.metadata = metadata;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(Instant expiresAt) {
        this.expiresAt = expiresAt;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}